# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core_output.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import state_pb2 as state__pb2
import control_pb2 as control__pb2
import state_extend_pb2 as state__extend__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ore_output.proto\x12\x0b\x63ore_output\x1a\x0bstate.proto\x1a\rcontrol.proto\x1a\x12state_extend.proto\"D\n\x0bViewMessage\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\'\n\x06output\x18\x02 \x01(\x0b\x32\x17.core_output.CoreOutput\"\x8c\x01\n\nCoreOutput\x12\x1b\n\x05state\x18\x01 \x01(\x0b\x32\x0c.state.State\x12!\n\x07\x63ontrol\x18\x02 \x01(\x0b\x32\x10.control.Control\x12\r\n\x05\x64_lef\x18\x03 \x01(\x01\x12/\n\x0cstate_extend\x18\x04 \x01(\x0b\x32\x19.state_extend.StateExtendb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_output_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIEWMESSAGE']._serialized_start=82
  _globals['_VIEWMESSAGE']._serialized_end=150
  _globals['_COREOUTPUT']._serialized_start=153
  _globals['_COREOUTPUT']._serialized_end=293
# @@protoc_insertion_point(module_scope)
