# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\x05state\"\xae\x01\n\x05State\x12\x0c\n\x04npos\x18\x01 \x01(\x01\x12\x0c\n\x04\x65pos\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\x12\x0b\n\x03phi\x18\x04 \x01(\x01\x12\r\n\x05theta\x18\x05 \x01(\x01\x12\x0b\n\x03psi\x18\x06 \x01(\x01\x12\x10\n\x08velocity\x18\x07 \x01(\x01\x12\r\n\x05\x61lpha\x18\x08 \x01(\x01\x12\x0c\n\x04\x62\x65ta\x18\t \x01(\x01\x12\t\n\x01p\x18\n \x01(\x01\x12\t\n\x01q\x18\x0b \x01(\x01\x12\t\n\x01r\x18\x0c \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATE']._serialized_start=23
  _globals['_STATE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
