[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tcp"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.9.6", features = ["lua54", "module"] }
